name: Single-Page Application
description: Provides all of the internet banking functionality to the customers via their web browser.
technology: JavaScript and Angular
components:
  webApp:
    name: Banking SPA
    relationships:
      - type: uses 
        target:
          $ref: "../../Component/Internet Banking System/Sign-In-Controller.yaml"
      - type: uses 
        target:
          $ref: "../../Component/Internet Banking System/Reset-Password-Controller.yaml"
      - type: uses 
        target:
          $ref: "../../Component/Internet Banking System/Accounts-Summary-Controller.yaml"
    