@startuml Network Diagram Appointments
header Network Diagram
title Appointments
node "Mobile App" as Mobile_App <<Device>> {
}
node "Application Server" as Application_Server <<Device>> {
}
node "Database Server" as Database_Server <<Device>> {
}
	Mobile_App .down-> Application_Server: <<Uses>>\nPorts: 443\nProtcol:TCP
	Application_Server .down-> Database_Server: <<Uses>>\nPorts: 1443\nProtcol:TCP
@enduml

''''''''''''''''''''''''''''''
@startuml Deployment Diagram Appointments
header Deployment Diagram
title Appointments
node "Mobile App" as Mobile_App <<Device>> {
	boundary "Appointments App" as Appointments_Appointments_App <<UI>>
}
node "Application Server" as Application_Server <<Device>> {
	component "Appointments Service" as Appointments_Appointments_Service <<Service>> {
	}
}
node "Database Server" as Database_Server <<Device>> {
	database "Appointments Database" as Appointments_Appointments_Database <<Database>>
}
	Appointments_Appointments_App .down-> Appointments_Appointments_Service: <<Uses>>
	Appointments_Appointments_Service .down-> Appointments_Appointments_Database: <<Uses>>
@enduml

''''''''''''''''''''''''''''''
@startuml Component Diagram Appointments
header Component Diagram
title Appointments
package "Appointments" as Appointments_package <<System>>{
	boundary "Appointments App" as Appointments_Appointments_App <<UI>>
	component "Appointments Service" as Appointments_Appointments_Service <<Service>> {
		interface "subscribe" as subscribe
	}
	database "Appointments Database" as Appointments_Appointments_Database <<Database>>
}
	Appointments_Appointments_App .down-> Appointments_Appointments_Service: <<Uses>>
	Appointments_Appointments_Service .down-> Appointments_Appointments_Database: <<Uses>>
@enduml
