@startuml Network Diagram Catalog
header Network Diagram
title Catalog
node "Virtual Network" as Virtual_Network <<Domain>> {
	node "Kubernetes Cluster" as Kubernetes_Cluster <<Execution Environment>> {
		node "Catalog Container" as Catalog_Catalog_Container <<Execution Environment>> {
		}
	}
	node "SQL Database Server" as SQL_Database_Server <<Device>> {
		node "SQL RDBMS" as SQL_RDBMS <<Execution Environment>> {
		}
	}
}
@enduml

''''''''''''''''''''''''''''''
@startuml Deployment Diagram Catalog
header Deployment Diagram
title Catalog
node "Virtual Network" as Virtual_Network <<Domain>> {
	node "Kubernetes Cluster" as Kubernetes_Cluster <<Execution Environment>> {
		queue "Event Bus (Pub/Sub)" as Event_Bus_Event_Bus_Pub_Sub <<Queue>> {
			interface "publish" as Event_Bus_publish
		}
		node "Catalog Container" as Catalog_Catalog_Container <<Execution Environment>> {
			component "Catalog Service" as Catalog_Catalog_Service <<Service>> {
			}
		}
	}
	node "SQL Database Server" as SQL_Database_Server <<Device>> {
		node "SQL RDBMS" as SQL_RDBMS <<Execution Environment>> {
			database "Catalog DB (SQL)" as Catalog_Catalog_DB_SQL <<Database>>
		}
	}
}
	Catalog_Catalog_Service -down-> Catalog_Catalog_DB_SQL: <<Accesses>>
	Catalog_Catalog_Service -down-> Event_Bus_publish: <<Accesses>>
@enduml

''''''''''''''''''''''''''''''
@startuml Component Diagram Catalog
header Component Diagram
title Catalog
package "Catalog" as Catalog_package <<System>>{
	component "Catalog Service" as Catalog_Catalog_Service <<Service>> {
		interface "subscribe" as subscribe
	}
	database "Catalog DB (SQL)" as Catalog_Catalog_DB_SQL <<Database>>
}
	Catalog_Catalog_Service -down-> Catalog_Catalog_DB_SQL: <<Accesses>>
	Catalog_Catalog_Service -down-> Event_Bus_publish: <<Accesses>>
@enduml
