@startuml Network Diagram My System
header Network Diagram
title My System
node "Home" as Home <<Domain>> {
node "My Mobile Device" as My_Mobile_Device <<Device>> {
node "My Mobile OS" as My_Mobile_OS <<Execution Environment>> {

}
}
}
node "Datacenter" as Datacenter <<Domain>> {
node "API Gateway" as API_Gateway <<Device>> {
node "API Gateway Container" as API_Gateway_Container <<Device>> {


}
}
node "Application Server" as Application_Server <<Device>> {
node "Application Container" as Application_Container <<Device>> {

}

}
node "Database Server" as Database_Server <<Device>> {
node "RDBMS" as RDBMS <<Execution Environment>> {


}
}
}
My_Mobile_OS -- API_Gateway: Ports: 443\nProtocol:TCP
API_Gateway -- Application_Server: Ports: 80\nProtocol:TCP
Application_Server -- Database_Server: Ports:1433\nProtocol:TCP
@enduml

''''''''''''''''''''''''''''''
@startuml Deployment Diagram My System
header Network Diagram
title My System
node "Home" as Home <<Domain>> {
node "My Mobile Device" as My_Mobile_Device <<Device>> {
node "My Mobile OS" as My_Mobile_OS <<Execution Environment>> {
boundary "My Application" as My_Application <<UI>>
}
}
}
node "Datacenter" as Datacenter <<Domain>> {
node "API Gateway" as API_Gateway <<Device>> {
node "API Gateway Container" as API_Gateway_Container <<Device>> {
interface "Corporate" as Corporate
interface "Public" as Public
}
}
node "Application Server" as Application_Server <<Device>> {
node "Application Container" as Application_Container <<Device>> {
component "My Service" as My_Service <<Service>>
}
interface "Internal" as Internal
}
node "Database Server" as Database_Server <<Device>> {
node "RDBMS" as RDBMS <<Execution Environment>> {
database "My Database" as My_Database <<Database>>
database "My Database2" as My_Database2 <<Database>>
}
}
}
My_Application -down-( Corporate
Corporate -down-( Internal
Public -down-( Internal
My_Service -up- Internal
My_Service .down-> My_Database: <<CRUD>>
My_Service .down-> My_Database2: <<CRUD>>
@enduml

''''''''''''''''''''''''''''''
@startuml Component Diagram My System
package "My System" as My_System_package <<System>>{
header Component Diagram
title My System
boundary "My Application" as My_Application <<UI>>



interface "Corporate" as Corporate
interface "Public" as Public


component "My Service" as My_Service <<Service>>

interface "Internal" as Internal

database "My Database" as My_Database <<Database>>
database "My Database2" as My_Database2 <<Database>>



My_Application -down-( Corporate
Corporate -down-( Internal
Public -down-( Internal
My_Service -up- Internal
My_Service .down-> My_Database: <<CRUD>>
My_Service .down-> My_Database2: <<CRUD>>

}
@enduml

''''''''''''''''''''''''''''''
@startuml System Diagram My System
header System Diagram
title My System
package "My System" as My_System_package <<System>>
@enduml
