@startuml Network Diagram Ordering
header Network Diagram
title Ordering
node "Virtual Network" as Virtual_Network <<Domain>> {
	node "Kubernetes Cluster" as Kubernetes_Cluster <<Execution Environment>> {
		node "Ordering Container" as Ordering_Ordering_Container <<Execution Environment>> {
		}
	}
	node "SQL Database Server" as SQL_Database_Server <<Device>> {
		node "SQL RDBMS" as SQL_RDBMS <<Execution Environment>> {
		}
	}
}
@enduml

''''''''''''''''''''''''''''''
@startuml Deployment Diagram Ordering
header Deployment Diagram
title Ordering
node "Virtual Network" as Virtual_Network <<Domain>> {
	node "Kubernetes Cluster" as Kubernetes_Cluster <<Execution Environment>> {
		queue "Event Bus (Pub/Sub)" as Event_Bus_Event_Bus_Pub_Sub <<Queue>> {
			interface "publish" as Event_Bus_publish
		}
		node "Ordering Container" as Ordering_Ordering_Container <<Execution Environment>> {
			component "Ordering Service" as Ordering_Ordering_Service <<Service>> {
			}
			control "Ordering Background Tasks" as Ordering_Ordering_Background_Tasks <<Processor>>
		}
	}
	node "SQL Database Server" as SQL_Database_Server <<Device>> {
		node "SQL RDBMS" as SQL_RDBMS <<Execution Environment>> {
			database "Ordering DB (SQL)" as Ordering_Ordering_DB_SQL <<Database>>
		}
	}
}
	Ordering_Ordering_Service -down-> Ordering_Ordering_DB_SQL: <<Accesses>>
	Ordering_Ordering_Background_Tasks -down-> Ordering_Ordering_DB_SQL: <<Accesses>>
	Ordering_Ordering_Service -down-> Event_Bus_publish: <<Accesses>>
@enduml

''''''''''''''''''''''''''''''
@startuml Component Diagram Ordering
header Component Diagram
title Ordering
package "Ordering" as Ordering_package <<System>>{
	component "Ordering Service" as Ordering_Ordering_Service <<Service>> {
		interface "subscribe" as subscribe
	}
	control "Ordering Background Tasks" as Ordering_Ordering_Background_Tasks <<Processor>>
	database "Ordering DB (SQL)" as Ordering_Ordering_DB_SQL <<Database>>
}
	Ordering_Ordering_Service -down-> Ordering_Ordering_DB_SQL: <<Accesses>>
	Ordering_Ordering_Background_Tasks -down-> Ordering_Ordering_DB_SQL: <<Accesses>>
	Ordering_Ordering_Service -down-> Event_Bus_publish: <<Accesses>>
@enduml
